default:
  tags:
    - k8s
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure
      - scheduler_failure
  before_script:
    - cp -r /docs/. /builds/ndx/product/product-doc  
    - env
    - pwd
    - ls -al
    - whoami
    - ls /home
    - ls /
  image:
    name: release-ci.daocloud.io/product/ndx-mkdocs-material:3.1.3
    entrypoint: [""]

stages:
  - test
  - build

pages:
  stage: build
  only:
    - master
  script:
    - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - apk add bash
    - pip install -r requirements.txt -i http://pypi.douban.com/simple --trusted-host pypi.douban.com
    - mkdocs build -d public # build to public path
  artifacts:
    paths:
      - public
    expire_in: 1 week
