variables:
  GIT_SUBMODULE_STRATEGY: recursive # 拉取 Submodule 内容

default:
  tags:
    - k8s
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure
      - scheduler_failure
  before_script:
    - cp -r /docs/. /builds/ndx/product/product-doc  
    - env
    - pwd
    - ls -al
    - whoami
    - ls /
  image:
    name: release-ci.daocloud.io/product/ndx-mkdocs-material:3.1.3
    entrypoint: [""]

stages:
  - test
  - build

pages:
  stage: build
  only:
    - master
  script:
    # - eval sed -i -e 's/yjXVPD6vyDFkC6fTsnWS/$GH_TOKEN/g' mkdocs.yml # 不需要使用 token， 直接通过相对路径拉取
    - apk add bash
    - pip install mkdocs-monorepo-plugin jieba -i http://pypi.douban.com/simple --trusted-host pypi.douban.com
    - mkdocs build -d public # build to public path
  artifacts:
    paths:
      - public
    expire_in: 1 week
