variables:
  GIT_SUBMODULE_STRATEGY: recursive # 拉取 Submodule 内容

default:
  tags:
    - k8s
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure
      - scheduler_failure
  image:
    name: release-ci.daocloud.io/product/ndx-mkdocs-material:3.1.3
    entrypoint: [""]

  before_script:
    - cp -r /docs/. /builds/ndx/product/product-doc
    - env
    - pwd
    - ls -al
    - whoami
    - ls /

stages:
  - build_docs
  - build_images

pages:
  stage: build_docs
  only:
    - master
  script:
    - apk add bash
    - pip install mkdocs-monorepo-plugin jieba -i http://pypi.douban.com/simple --trusted-host pypi.douban.com
    - mkdocs build -f mkdocs-zh.yml -d public/ # build to public path
    - mkdocs build -f mkdocs-en.yml -d public/en/ # build to public path
  artifacts:
    paths:
      - public
    expire_in: 1 week
  cache:
    key: build-cache
    paths:
      - public

images:
  image: release-ci.daocloud.io/common-ci/common-ci-builder:v0.1.15
  stage: build_images
  cache:
    key: build-cache
    paths:
      - public
  services:
    - docker:dind
  before_script:
    - docker -v
  script:
    - ls -al
    - export REGISTRY_SERVER_ADDRESS="release-ci.daocloud.io"
    - docker login -u ${REGISTRY_USER_NAME} -p ${REGISTRY_PASSWORD} ${REGISTRY_SERVER_ADDRESS}
    - docker build -t release-ci.daocloud.io/product/dce5-docs:latest -f Dockerfile_images .
    - docker push release-ci.daocloud.io/product/dce5-docs:latest
  # Run this job in a branch where a Dockerfile exists
  rules:
    - if: $CI_COMMIT_BRANCH
      exists:
        - Dockerfile_images
